# -*- coding: utf-8 -*-
"""Group_6_EE656.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/150Cqx5IsEGFJDVxG2YOOJQNj-L9FfZPX
"""

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

"""# Normalization to a unit hypercube"""

def min_max_normalize(X):
    X_min = np.min(X, axis=0)
    X_max = np.max(X, axis=0)
    denominator = X_max - X_min
    denominator[denominator == 0] = 1e-10
    return (X - X_min) / denominator

def sq_euclidean(a, b):
    return np.sum((a - b) ** 2)

"""# Cluster wise Silhouette & Global Silhouette Index"""

from sklearn import metrics
def calculate_silhouette(X, labels, num_clusters):
    Labels =labels.astype(int)
    # Sample-wise Silhouette values
    sample_si = metrics.silhouette_samples(
        X.astype(np.float64),
        Labels,
        metric="sqeuclidean"
    )

    # Cluster-wise Silhouette Index
    S_m = np.zeros(num_clusters)

    for cluster in range(num_clusters):

        cluster_scores = sample_si[Labels == cluster]

        if len(cluster_scores) > 0:
            S_m[cluster] = np.mean(cluster_scores)

    # Global Silhouette Index
    GSI = np.mean(sample_si)

    return S_m, GSI

"""# Lagrange Interpolation"""

# Lagrange Interpolation
# Constructs the Threshold–SI interpolation polynomial
# using (δm , Sm) pairs (Paper Equations 8–10)


def lagrange_interpolate(delta_m, S_m, delta):

   # delta_m : Threshold values (δ1, δ2, ..., δM)
   # S_m : Cluster-wise Silhouette Index   (S1, S2, ..., SM)
   #delta : Threshold at which the interpolation polynomial is evaluated

   # Number of interpolation points
    M = len(delta_m)

    # Interpolated SI value
    S_delta = 0.0

    # Compute Lagrange interpolation polynomial
    for i in range(M):

        # ith Lagrange basis polynomial
        L_i = S_m[i]

        for j in range(M):

            if i != j:

                denominator = delta_m[i] - delta_m[j]

                # Avoid division by zero
                if denominator == 0:
                    denominator = 1e-10

                L_i *= (delta - delta_m[j]) / denominator

        S_delta += L_i

  # S(delta) : Interpolated Silhouette value  at the current threshold delta using this updated  relationship
    return S_delta

"""Optimal Threshold(η)"""

# Steps11-13: Find the Optimal Threshold (η)
#
# Step 11 :Set the desired Silhouette value S(δ) = 1
# Step 12 :Evaluate the Lagrange interpolation polynomial
#           over the threshold search interval
# Step 13 : Select the threshold η for which |S(δ) - 1| is minimum



def find_optimal_threshold(delta_m, S_m):


    # delta_m : Threshold values (δ1, δ2, ..., δM)

    # S_m : Cluster-wise Silhouette Index
    # (S1, S2, ..., SM)

    # Desired Silhouette value
    target_S = 1.0

    # Search interval for threshold
    delta_min = 0.0
    delta_max = np.max(delta_m) * 2

    search_delta = np.linspace(
        delta_min,
        delta_max,
        1000
    )

    # Initialize optimum threshold
    eta = delta_min

    # Initialize minimum interpolation error
    minimum_error = np.inf

    # Evaluate interpolation polynomial
    for delta in search_delta:

        # Predicted Silhouette value S(δ)
        S_predicted = lagrange_interpolate(
            delta_m,
            S_m,
            delta
        )

        # Difference from ideal value
        interpolation_error = abs(
            S_predicted - target_S
        )

        # Update optimum threshold
        if interpolation_error < minimum_error:

            minimum_error = interpolation_error
            eta = delta

    # eta : Optimized threshold (η)
    return eta

"""# SOC- Pipeline"""

# Self-Optimal Clustering (SOC)
# This class implements the complete SOC algorithm proposed in the paper.
class SOC_Algorithm:
 # Initialize SOC parameters
    def __init__(self, M_clusters, max_iterations=10):
        # Number of clusters (M)
        self.M = M_clusters
        # Maximum SOC optimization iterations
        self.max_iter = max_iterations
        # Best Global Silhouette Index
        self.best_GSI = -1.0
        # Best clustering result
        self.best_labels = None
        # Best cluster centers
        self.best_centers = None


    #Threshold Function
    # Computes the initial threshold (δ)
    def _calculate_base_delta(self, X_norm):
        # Number of samples
        num_samples = len(X_norm)
        threshold_sum = 0.0
        for sample in range(num_samples):
          minimum_feature = np.min(X_norm[sample])
          feature_sum = np.sum(X_norm[sample])
          if feature_sum != 0:
            threshold_sum += (minimum_feature /feature_sum)
        base_delta = (1 / (2 * num_samples)) * threshold_sum
        return base_delta


    # Execute Self-Optimal Clustering
    def fit(self, X_raw):
        # Step 1 : Normalize data
        X_norm = min_max_normalize(X_raw)
        num_samples = len(X_norm)
        # Initialize optimization factor βm
        # Initially βm = 1
        beta_m = np.ones(self.M)

       # Step 2 : Compute initial threshold (δ)
        base_delta = self._calculate_base_delta(X_norm)
        # Store GSI of every SOC iteration
        history = {"Threshold": [],"Eta": [],"Beta": [],"GSI": [],"Sm": []}

        # SOC Optimization Loop
        for iteration in range(self.max_iter):
            # Step 2
            # Compute threshold for every cluster
            # δm = δ × βm
            delta_m = base_delta * beta_m
            # Cluster centers
            cluster_centers = []
            # Cluster labels
            cluster_labels = np.full(num_samples,-1 )
            # Initially all samples are active
            remaining_indices = np.arange(num_samples)

            # Steps 3 - 8
            # Improved Mountain Clustering (IMC)
            # for M clusters
            for cluster in range(self.M):
                # Stop if all samples are assigned
                if len(remaining_indices) == 0:
                   break
                # Remaining data points
                remaining_points = X_norm[remaining_indices]

                # Step 3
                # Compute Mountain Potential
                mountain_potential = np.zeros(len(remaining_points))
                for point in range(len(remaining_points)):
                    squared_distance = np.sum(( remaining_points -remaining_points[point]) ** 2,axis=1)
                    mountain_potential[point] = np.sum(np.exp(-squared_distance /(delta_m[cluster] ** 2)))

                # Step 4
                # Select point with maximum potential
                # as the cluster center
                center_index = np.argmax(mountain_potential)

                cluster_center = remaining_points[center_index]
                cluster_centers.append(cluster_center)

                # Steps 5-7
                # Assign samples lying inside δm
                # Remove assigned samples
                # Continue with remaining samples
                updated_remaining = []
                for sample_index in remaining_indices:
                       distance = sq_euclidean(X_norm[sample_index],cluster_center)
                       if distance <= delta_m[cluster]:
                        cluster_labels[sample_index] = cluster
                       else:
                        updated_remaining.append(sample_index)
                # Remaining samples for next cluster
                remaining_indices = np.array(updated_remaining)

            # Step 8 : Assign Remaining Samples
            # Assign all unclustered samples to the nearest
            # cluster center using squared Euclidean distance.
            for sample_index in remaining_indices:
                  distance_to_centers = [
                             sq_euclidean(
                             X_norm[sample_index],
                            center) for center in cluster_centers]

                  cluster_labels[sample_index] = np.argmin(distance_to_centers)

            # At this point IMC clustering is done

            # Step 9 : Compute Cluster-wise Silhouette Index
            # Calculates:
            #   Sm  : Silhouette Index of each cluster
            #   GSI : Global Silhouette Index
            S_m, GSI = calculate_silhouette(X_norm, cluster_labels,len(cluster_centers))

            # Store GSI of current SOC iteration
            history["GSI"].append(GSI)
            history["Threshold"].append(delta_m.copy())
            # history["Eta"].append(eta)
            # history["Beta"].append(beta_m.copy())
            history["Sm"].append(S_m.copy())



            # Store the best clustering obtained so far.
            # The paper selects the clustering corresponding
            # to the maximum GSI.
            if GSI > self.best_GSI:
                 self.best_GSI = GSI
                 self.best_labels = cluster_labels.copy()
                 self.best_centers = np.array(cluster_centers)


            # Steps 10 - 15
            # Threshold Optimization using
            if iteration < self.max_iter - 1:
               # Compute the optimized threshold (η)
               # using the Threshold–SI interpolation polynomial.
               eta = find_optimal_threshold(delta_m,S_m)

               history["Eta"].append(eta)
               history["Beta"].append(beta_m.copy())


                # Step 14
                # Compute Optimization Factor
                # βm = η / δm
               for cluster in range(self.M):
                    if delta_m[cluster] > 0:
                      beta_m[cluster] = (eta /delta_m[cluster])




                # Step 15
                # Updated βm is used in the next SOC iteration
                # to compute the new threshold values.
                # Return Final SOC Result


        return (self.best_labels, self.best_centers,history)
print("SOC Pipeline Done")

"""# Experimental - **Setup**"""

# Upload Multiple Test Images


import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

uploaded = files.upload()

TARGET_SIZE = (80,80)

images = []
image_names = []

for filename in uploaded.keys():

    image = cv2.imread(filename)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image = cv2.resize(image, TARGET_SIZE)

    images.append(image)
    image_names.append(filename)

print(f"Total Images Uploaded : {len(images)}")

"""# Running SOC on the  5 natural images + **2**-color image to get plots (GSI v/s No . of clusters , GSI v/s iterations) , segemented images , table of 10 iterations for optimal no. of clusters."""

import pandas as pd
for image_number, image in enumerate(images):

                  print("="*80)
                  print(f"IMAGE {image_number+1}")
                  print(image_names[image_number])
                  print("="*80)

                  rows, cols, channels = image.shape

                  X = image.reshape((-1,3)).astype(np.float64)








                  print("Image Shape :",image.shape)
                  print("Feature Matrix :",X.shape)

                  cluster_candidates = [2,3,4,5]
                  experiment_results = {}
                  best_GSI = -np.inf
                  optimal_clusters = None
                  best_labels = None
                  best_centers = None
                  best_history = None


                  for M in cluster_candidates:
                      print("="*60)
                      print(f"Running SOC for M = {M}")
                      print("="*60)

                      soc = SOC_Algorithm( M_clusters=M,max_iterations=10)
                      labels, centers, history = soc.fit(X)
                      print(soc.best_GSI)
                      experiment_results[M] = {"labels": labels,"centers": centers,"history": history,"GSI": soc.best_GSI}
                      if soc.best_GSI > best_GSI:
                          best_GSI = soc.best_GSI
                          optimal_clusters = M
                          best_labels = labels
                          best_centers = centers
                          best_history = history

                  print("="*60)
                  print("Experimental Results")
                  print("="*60)
                  print("Optimal Number of Clusters :",optimal_clusters)
                  print("Maximum Global SI :",round(best_GSI,4))
                  print("="*60)


                  segmented = best_centers[best_labels.astype(int)]

                  # Convert back to 0–255
                  segmented = (segmented * 255).clip(0,255)

                  segmented = segmented.reshape(rows, cols, channels)





                  plt.figure(figsize=(12,5))

                  plt.subplot(121)
                  plt.imshow(image)
                  plt.title(f"Original Image\n{image_names[image_number]}")
                  plt.axis("off")

                  plt.subplot(122)
                  plt.imshow(segmented.astype(np.uint8))
                  plt.title(f"SOC Segmentation\n{image_names[image_number]} (M={optimal_clusters})")
                  plt.axis("off")

                  plt.show()








                  # Plot 1 : Global Silhouette Index vs Number of Clusters
                  cluster_list = sorted(experiment_results.keys())
                  gsi_values = [experiment_results[m]["GSI"] for m in cluster_list]
                  plt.figure(figsize=(6,4))
                  plt.plot(cluster_list, gsi_values, marker='o', linewidth=2)
                  plt.xlabel("Number of Clusters (M)")
                  plt.ylabel("Maximum Global Silhouette Index (GSI)")
                  plt.title(f"GSI vs Number of Clusters\n{image_names[image_number]}")
                  plt.grid(True)
                  plt.show()


                  # Plot 2 : GSI vs Iteration (Optimal Cluster Only)
                  optimal_history = best_history
                  iterations = np.arange(
                      1,
                      len(optimal_history["GSI"]) + 1
                  )
                  plt.figure(figsize=(6,4))
                  plt.plot(
                      iterations,
                      optimal_history["GSI"],
                      marker='o',
                      linewidth=2
                  )

                  plt.xlabel("SOC Iteration")
                  plt.ylabel("Global Silhouette Index (GSI)")
                  plt.title(f"GSI vs Iteration\n{image_names[image_number]} (M={optimal_clusters})")
                  plt.grid(True)
                  plt.show()



                  # Iteration-wise SOC Result Table
                  rows = []
                  for i in range(len(optimal_history["GSI"])):

                      rows.append({

                          "Iteration" : i + 1,

                          "Threshold δm" :
                          np.round(optimal_history["Threshold"][i],5),

                          "Cluster SI (Sm)" :
                          np.round(optimal_history["Sm"][i],4),

                          "GSI" :
                          round(optimal_history["GSI"][i],4),

                          "η (Optimal Threshold)" :
                          (
                              round(optimal_history["Eta"][i],5)
                              if i < len(optimal_history["Eta"])
                              else "-"
                          ),

                          "βm" :
                          (
                              np.round(optimal_history["Beta"][i],4)
                              if i < len(optimal_history["Beta"])
                              else "-"
                          )

                      })

                  results_table = pd.DataFrame(rows)

                  print("="*80)
                  print("="*80)
                  print(f"Image : {image_names[image_number]}")
                  print(f"Optimal Number of Clusters : {optimal_clusters}")
                  print(f"Maximum GSI : {best_GSI:.4f}")
                  print("="*80)
                  print("="*80)

                  display(results_table)
                  print("="*100)
                  print("End of Image", image_number + 1)
                  print("="*100)

                  results_table.to_csv(f"SOC_Results_{image_names[image_number].split('.')[0]}.csv",index=False)

"""# Comparsions with other existing clustering techniques on the basis of several cluseter quality metrics"""

import pandas as pd
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture
try:
    import skfuzzy as fuzz
except:
    import subprocess
    subprocess.run(['pip','install','scikit-fuzzy','-q'])
    import skfuzzy as fuzz


def partition_index(X, labels, centres):
    M = len(centres)
    pi = 0.0
    for m in range(M):
        mask = (labels == m)
        if not mask.any():
            continue
        intra = np.sum(np.linalg.norm(X[mask] - centres[m], axis=1) ** 2)
        Nm = int(mask.sum())
        inter = sum(np.linalg.norm(centres[k] - centres[m]) ** 2 for k in range(M) if k != m)
        if inter > 0 and Nm > 0:
            pi += intra / (Nm * inter)
    return pi

def separation_index(X, labels, centres):
    M = len(centres)
    pairs = [np.linalg.norm(centres[m] - centres[k]) ** 2
             for m in range(M) for k in range(M) if m != k]
    min_inter = min(pairs) if pairs else 1e-9
    if min_inter == 0:
        return np.inf
    total_intra = sum(
        np.sum(np.linalg.norm(X[labels == m] - centres[m], axis=1) ** 2)
        for m in range(M) if (labels == m).any()
    )
    return total_intra / (len(X) * min_inter)

def dunn_index(X, labels, centres):
    M = len(centres)
    diameters = []
    for m in range(M):
        pts = X[labels == m]
        if len(pts) < 2:
            diameters.append(0.0)
            continue
        d = pts[:, np.newaxis, :] - pts[np.newaxis, :, :]
        diameters.append(np.sqrt((d ** 2).sum(axis=2)).max())
    max_d = max(diameters) if max(diameters) > 0 else 1e-9
    min_r = np.inf
    for m in range(M):
        pm = X[labels == m]
        if not len(pm):
            continue
        for k in range(M):
            if k == m:
                continue
            pk = X[labels == k]
            if not len(pk):
                continue
            d_inter = (
                np.linalg.norm(pm - centres[m], axis=1).sum() +
                np.linalg.norm(pk - centres[k], axis=1).sum()
            ) / (len(pm) + len(pk))
            min_r = min(min_r, d_inter / max_d)
    return float(min_r) if min_r != np.inf else 0.0

def run_imc1(X_norm, M):
    soc = SOC_Algorithm(M_clusters=M, max_iterations=1)
    soc.fit(X_norm * 255)
    return soc.best_labels, soc.best_centers

def run_imc2(X_norm, M):
    class IMC2:
        def __init__(self, M):
            self.M = M
            self.best_labels = None
            self.best_centers = None
        def fit(self, X_raw):
            X_norm = min_max_normalize(X_raw)
            n = len(X_norm)
            beta_m = np.array([(m + 1) / (m + 2) for m in range(self.M)])
            base_delta = max(
                (1 / (2 * n)) * sum(
                    np.min(X_norm[s]) / np.sum(X_norm[s])
                    for s in range(n) if np.sum(X_norm[s]) > 1e-10
                ), 1e-9
            )
            delta_m = base_delta * beta_m
            cluster_centers = []
            cluster_labels = np.full(n, -1)
            remaining = np.arange(n)
            for cluster in range(self.M):
                if len(remaining) == 0:
                    break
                rpts = X_norm[remaining]
                pot = np.zeros(len(rpts))
                for pt in range(len(rpts)):
                    sq_d = np.sum((rpts - rpts[pt]) ** 2, axis=1)
                    pot[pt] = np.sum(np.exp(-sq_d / (delta_m[cluster] ** 2)))
                center = rpts[np.argmax(pot)]
                cluster_centers.append(center)
                upd = []
                for si in remaining:
                    if np.sum((X_norm[si] - center) ** 2) <= delta_m[cluster]:
                        cluster_labels[si] = cluster
                    else:
                        upd.append(si)
                remaining = np.array(upd)
            cc = np.array(cluster_centers) if cluster_centers else np.zeros((1, X_norm.shape[1]))
            for si in remaining:
                cluster_labels[si] = np.argmin([np.sum((X_norm[si] - c) ** 2) for c in cc])
            self.best_labels = cluster_labels
            self.best_centers = cc
    m = IMC2(M)
    m.fit(X_norm * 255)
    return m.best_labels, m.best_centers

def reconstruct_image(centers_norm, labels, x_min, x_max, rows, cols, channels):
    denom = np.where(x_max - x_min == 0, 1, x_max - x_min)
    centers_raw = (centers_norm * denom + x_min).clip(0, 255).astype(np.uint8)
    return centers_raw[labels.astype(int)].reshape(rows, cols, channels)


for image_number, image in enumerate(images):

    print("=" * 80)
    print(f"IMAGE {image_number + 1} : {image_names[image_number]}")
    print("=" * 80)

    rows_img, cols_img, channels_img = image.shape
    X_raw = image.reshape(-1, 3).astype(np.float64)
    x_min = X_raw.min(axis=0)
    x_max = X_raw.max(axis=0)
    X_norm = min_max_normalize(X_raw)

    cluster_candidates = [2, 3, 4, 5]
    exp_res = {}
    best_GSI_img = -np.inf
    opt_M = None
    opt_labels = None
    opt_centers = None

    for M in cluster_candidates:
        soc = SOC_Algorithm(M_clusters=M, max_iterations=10)
        lb, ct, hist = soc.fit(X_raw)
        exp_res[M] = {"labels": lb, "centers": ct, "GSI": soc.best_GSI}
        if soc.best_GSI > best_GSI_img:
            best_GSI_img = soc.best_GSI
            opt_M = M
            opt_labels = lb
            opt_centers = ct

    print(f"Optimal Number of Clusters : {opt_M}")
    print(f"Maximum SOC GSI            : {round(best_GSI_img, 4)}")

    M_use = opt_M

    method_results = {}

    km = KMeans(n_clusters=M_use, random_state=42, n_init=10).fit(X_norm)
    method_results["K-Means"] = (km.labels_, km.cluster_centers_)

    try:
        cntr, u, *_ = fuzz.cluster.cmeans(X_norm.T, M_use, 2, error=0.005, maxiter=500, seed=42)
        method_results["FCM"] = (np.argmax(u, axis=0), cntr)
    except Exception:
        method_results["FCM"] = (km.labels_, km.cluster_centers_)

    gm = GaussianMixture(n_components=M_use, random_state=42).fit(X_norm)
    method_results["EM"] = (gm.predict(X_norm), gm.means_)

    imc1_lb, imc1_ct = run_imc1(X_norm, M_use)
    method_results["IMC-1"] = (imc1_lb, imc1_ct)

    imc2_lb, imc2_ct = run_imc2(X_norm, M_use)
    method_results["IMC-2"] = (imc2_lb, imc2_ct)

    method_results["SOC"] = (opt_labels, opt_centers)

    table_rows = []
    for method_name, (lb, ct) in method_results.items():
        try:
            lb_int = lb.astype(int)
            ct_arr = np.array(ct)
            n_cl = len(ct_arr)
            _, gsi_v = calculate_silhouette(X_norm, lb_int, n_cl)
            pi_v = partition_index(X_norm, lb_int, ct_arr)
            si_v = separation_index(X_norm, lb_int, ct_arr)
            di_v = dunn_index(X_norm, lb_int, ct_arr)
        except Exception:
            gsi_v = pi_v = si_v = di_v = float('nan')
        table_rows.append({
            "Method": method_name,
            "GSI ↑": round(gsi_v, 4),
            "PI ↓": round(pi_v, 4),
            "SI ↓": round(si_v, 4),
            "DI ↑": round(di_v, 4),
        })

    df = pd.DataFrame(table_rows).set_index("Method")
    print(f"\nComparison Table (M={M_use}) — {image_names[image_number]}")
    print("=" * 60)
    display(df)
    print("=" * 60)
    print("GSI↑ higher=better | PI↓ lower=better | SI↓ lower=better | DI↑ higher=better")

    seg_methods = ["IMC-1", "IMC-2", "SOC"]
    fig, axes = plt.subplots(1, len(seg_methods) + 1, figsize=(5 * (len(seg_methods) + 1), 5))

    axes[0].imshow(image)
    axes[0].set_title(f"Original{image_names[image_number]}", fontsize=10)
    axes[0].axis("off")

    for ax, seg_name in zip(axes[1:], seg_methods):
        lb_s, ct_s = method_results[seg_name]
        seg_img = reconstruct_image(
            np.array(ct_s), lb_s.astype(int),
            x_min, x_max, rows_img, cols_img, channels_img
        )
        _, gsi_s = calculate_silhouette(X_norm, lb_s.astype(int), len(ct_s))
        color = "red" if seg_name == "SOC" else "black"
        fw = "bold" if seg_name == "SOC" else "normal"
        ax.imshow(seg_img)
        ax.set_title(f"{seg_name}\nGSI={gsi_s:.4f}", fontsize=10, color=color, fontweight=fw)
        for sp in ax.spines.values():
            sp.set_edgecolor("red" if seg_name == "SOC" else "lightgrey")
            sp.set_linewidth(3 if seg_name == "SOC" else 0.8)
        ax.axis("off")

    plt.suptitle(
        f"Segmentation — IMC-1 vs IMC-2 vs SOC\n{image_names[image_number]} (M={M_use})",
        fontsize=12, fontweight="bold"
    )
    plt.tight_layout()
    plt.show()

    print("=" * 100)
    print(f"End of Image {image_number + 1}")
    print("=" * 100)